version: "3.9"

services:
  scraper:
    build:
      context: ./scraper
    container_name: jobspy_scraper
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: jobspy_frontend
    ports:
      - "8501:8501"
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    depends_on:
      - scraper
    restart: unless-stopped
